### ISSUE TITLE
zookeeper watcher won't update haproxy config when adding/removing new node

### ISSUE THREAD

**Issue by hankya** [airbnb/synapse#137]
Had anyone ever get synapse+zookeeper+nerve working prperly?

I followed the document on this repo, and encountered a couple of issues:
- synapse works with yaml config file however the json format config file is provided
- there is a few config items that should have been array however it is a single line in example config
- finally i was able to fix above problem, however, when taking a service online or offline, the change does not reflect in haproxy

here is my setup,
- synapse config
```yaml
 haproxy:
  reload_command: "sudo service haproxy reload"
  config_file_path: "/etc/haproxy/haproxy.cfg"
  socket_file_path: "/var/haproxy/haproxy.sock"
  do_writes: True
  do_reloads: True
  do_socket: True
  global:
   - "daemon"
   - "user    haproxy"
   - "group   haproxy"
   - "maxconn 4096"
   - "log     127.0.0.1 local2 notice"
   - "stats   socket /var/haproxy/haproxy.sock mode 666 level admin"
  defaults:
   - "log      global"
   - "balance  roundrobin"
   - "timeout connect 5s"
   - "timeout client 1m"
   - "timeout server 1m"
  extra_sections:
   "listen stats :3212":
    - "mode http"
    - "stats enable"
    - "stats uri /"
    - "stats refresh 5s"
 services:
  hellox:
   discovery:
    method: "zookeeper"
    path: "/nerve/services/hello/services"
    hosts:
     - "localhost:2181"
   haproxy:
    port: 3214
    server_options: "check inter 2s rise 3 fall 2"
    listen:
     - "mode http"
```
- nerve config
```json
{
  "instance_id": "localhost",
  "services": {
    "hello": {
      "host": "localhost",
      "port": 3000,
      "reporter_type": "zookeeper",
      "zk_hosts": ["localhost:2181"],
      "zk_path": "/nerve/services/hello/services",
      "check_interval": 2,
      "checks": [
        {
          "type": "http",
          "uri": "/health",
          "timeout": 0.2,
          "rise": 3,
          "fall": 2
        }
      ]
    },
    "hello2": {
      "host": "localhost",
      "port": 2999,
      "reporter_type": "zookeeper",
      "zk_hosts": ["localhost:2181"],
      "zk_path": "/nerve/services/hello/services",
      "check_interval": 2,
      "checks": [
        {
          "type": "http",
          "uri": "/health",
          "timeout": 0.2,
          "rise": 3,
          "fall": 2
        }
      ]
    },
    "hello3": {
      "host": "localhost",
      "port": 2998,
      "reporter_type": "zookeeper",
      "zk_hosts": ["localhost:2181"],
      "zk_path": "/nerve/services/hello/services",
      "check_interval": 2,
      "checks": [
        {
          "type": "http",
          "uri": "/health",
          "timeout": 0.2,
          "rise": 3,
          "fall": 2
        }
      ]
    },
    "hello4": {
      "host": "localhost",
      "port": 2997,
      "reporter_type": "zookeeper",
      "zk_hosts": ["localhost:2181"],
      "zk_path": "/nerve/services/hello/services",
      "check_interval": 2,
      "checks": [
        {
          "type": "http",
          "uri": "/health",
          "timeout": 0.2,
          "rise": 3,
          "fall": 2
        }
      ]
    }
  }
}
```
zookeeper is listening on port 2181, when I start synapse, there is no service running, there is 0 backend entries in haproxy config, then I bring up a few services, I can see new entries get added to zookeeper by nerve but it seems synapse isn't get notified of this, or it didn't do anything to add the new service to haproxy.

Can anyone please suggest where I am doing wrong? thanks.
