### ISSUE TITLE
Unexpected error when migrating from Synapse-0.13.8 to Synapse-0.14.3

### ISSUE THREAD

**Issue by microwavedboy** [airbnb/synapse#229]
Gem version: 0.14.3
Ruby version: 2.4.0
OS version: Ubuntu 14.04 (Trusty)

```
/usr/local/rvm-ansible/gems/ruby-2.4.0@global/gems/synapse-0.14.3/lib/synapse/config_generator.rb:15:in `rescue in create': Specified a config generator of check_interval, which could not be found: cannot load such file -- synapse/config_generator/check_interval (ArgumentError)
	from /usr/local/rvm-ansible/gems/ruby-2.4.0@global/gems/synapse-0.14.3/lib/synapse/config_generator.rb:8:in `create'
	from /usr/local/rvm-ansible/gems/ruby-2.4.0@global/gems/synapse-0.14.3/lib/synapse.rb:99:in `block in create_config_generators'
	from /usr/local/rvm-ansible/gems/ruby-2.4.0@global/gems/synapse-0.14.3/lib/synapse.rb:96:in `each'
	from /usr/local/rvm-ansible/gems/ruby-2.4.0@global/gems/synapse-0.14.3/lib/synapse.rb:96:in `create_config_generators'
	from /usr/local/rvm-ansible/gems/ruby-2.4.0@global/gems/synapse-0.14.3/lib/synapse.rb:17:in `initialize'
	from /usr/local/rvm-ansible/gems/ruby-2.4.0@global/gems/synapse-0.14.3/bin/synapse:59:in `new'
	from /usr/local/rvm-ansible/gems/ruby-2.4.0@global/gems/synapse-0.14.3/bin/synapse:59:in `<top (required)>'
	from /usr/local/rvm-ansible/gems/ruby-2.4.0@global/bin/synapse:22:in `load'
	from /usr/local/rvm-ansible/gems/ruby-2.4.0@global/bin/synapse:22:in `<main>'
	from /usr/local/rvm-ansible/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm-ansible/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

Here's an example stanza from my synapse configuration that will generate this error:

```
check_interval: 30
max_checks: 0
haproxy:
    reload_command: "sudo service haproxy reload"
    bind_address: localhost
    config_file_path: "/etc/haproxy/haproxy.cfg"
    do_writes: "true"
    do_reloads: "true"
    global:
        - "daemon"
        - "user    haproxy"
        - "group   haproxy"
        - "maxconn 4096"
        - "log     /dev/log local2 debug"
        - "stats   socket /var/run/haproxy.sock"
    defaults:
        - "log global"
        - "log-format %ST\\ %Tt\\ %Tr\\ %B\\ %b\\ %s\\ %{+Q}r"

        - "balance  roundrobin"
        - "timeout connect 5000ms"
        - "timeout client 50000ms"
        - "timeout server 50000ms"
        - "mode http"

services:
    alert_api:
        default_servers:
            - name: "default-alert_api"
              host: "localhost"
              port: "39999"
        discovery:
            method: "ec2tag"
            tag_name: "environment"
            tag_value: "production"
            selector: i.tags.has_key? alert_api

            check_interval: 60
            aws_access_key_id: "REDACTED"
            aws_secret_access_key: "SUPER-SEKRIT"
            aws_region: "us-east-1"
        haproxy:
            server_port_override: "39999"
            port: "8999"
            server_options: "check inter 20000 fastinter 5000 "
            backend:
            - "mode http"
```
