### ISSUE TITLE
Missing discovery method when trying to create watcher

### ISSUE THREAD

**Issue by Jaykah** [airbnb/synapse#70]
Hello,

I am trying to get Synapse up and running, however, I have encountered the following error:

```
/usr/local/lib/ruby/gems/2.1.0/gems/synapse-0.10.0/lib/synapse/service_watcher.rb:24:in `create': Missing discovery method when trying to create watcher (ArgumentError)
    from /usr/local/lib/ruby/gems/2.1.0/gems/synapse-0.10.0/lib/synapse.rb:72:in `block in create_service_watchers'
    from /usr/local/lib/ruby/gems/2.1.0/gems/synapse-0.10.0/lib/synapse.rb:71:in `each'
    from /usr/local/lib/ruby/gems/2.1.0/gems/synapse-0.10.0/lib/synapse.rb:71:in `create_service_watchers'
    from /usr/local/lib/ruby/gems/2.1.0/gems/synapse-0.10.0/lib/synapse.rb:18:in `initialize'
    from /usr/local/lib/ruby/gems/2.1.0/gems/synapse-0.10.0/bin/synapse:59:in `new'
    from /usr/local/lib/ruby/gems/2.1.0/gems/synapse-0.10.0/bin/synapse:59:in `<top (required)>'
    from /usr/local/bin/synapse:23:in `load'
    from /usr/local/bin/synapse:23:in `<main>'
```

My config looks like this:

```

---
  services: 
    application: 
      default_servers: 
        - 
          name: "default-app"
          host: "111.111.111.111"
          port: 443
      discovery: 
        method: "zookeeper"
        path: "/services/application"
        hosts: 
          - "xhbtr.site.com:2181"
          - "xhbtr2.site.com:2181"
          - "xhbtr3.site.com:2181"
      haproxy: 
        port: 3214
        server_options: "check inter 2s rise 3 fall 2"
        listen: 
          - "mode http"
          - "option httpchk /health"
          - "http-check expect string OK"
    haproxy: 
      reload_command: "sudo service haproxy reload"
      config_file_path: "/etc/haproxy/haproxy.cfg"
      socket_file_path: "/var/haproxy/stats.sock"
      do_writes: true
      do_reloads: true
      do_socket: false
      global: 
        - "daemon"
        - "user haproxy"
        - "group haproxy"
        - "maxconn 4096"
        - "log     127.0.0.1 local0"
        - "log     127.0.0.1 local1 notice"
        - "stats   socket /var/haproxy/stats.sock mode 666 level admin"
      defaults: 
        - "log      global"
        - "option   dontlognull"
        - "maxconn  2000"
        - "retries  3"
        - "timeout  connect 5s"
        - "timeout  client  1m"
        - "timeout  server  1m"
        - "option   redispatch"
        - "balance  leastconn"
      extra_sections: 
        listen stats :3212: 
          - "mode http"
          - "stats enable"
          - "stats uri /"
          - "stats refresh 5s"
```

What am I missing?

Thanks!
